apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vprocache01
  name: vprocache01
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: vprocache01
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vprocache01
    spec:
      containers:
      - image: memcached
        name: vprocache01
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
