apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vproweb
  name: vproapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: vproapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vproapp
    spec:
      containers:
      - image: divakar2201/tomcatv2
        name: vproapp
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps
          name: vproappdata
      restartPolicy: Always
      volumes:
      - name: vproappdata
        persistentVolumeClaim:
          claimName: vproappdata
status: {}
