apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vproweb
  name: vproweb
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: vproweb
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vproweb
    spec:
      containers:
      - image: divakar2201/webv2
        name: vproweb
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
