apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vprodb
  name: vprodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: vprodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vprodb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: vprodbpass
        image: divakar2201/dbv2
        name: vprodb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vprodbdata
      restartPolicy: Always
      volumes:
      - name: vprodbdata
        persistentVolumeClaim:
          claimName: vprodbdata
status: {}
